apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-notification
  labels:
    app: quiz-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-notification
  template:
    metadata:
      labels:
        app: quiz-notification
    spec:
      containers:
        - name: quiz-notification
          image: quiz-notification:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5004
          env:
            - name: PORT
              value: "5004"
            - name: QUIZ_MANAGEMENT_GRPC
              valueFrom:
                configMapKeyRef:
                  name: quiz-notification-config
                  key: redis
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
