apiVersion: v1
kind: Service
metadata:
  name: quiz-notification
  annotations:
    tailscale.com/hostname: "quiz-notification"
    tailscale.com/expose: "true"
spec:
  type: NodePort
  ports:
    - port: 5004
      targetPort: 5004
      nodePort: 30504
      protocol: TCP
  selector:
    app: quiz-notification
